"Afeganistão" = "AF"
"África do Sul" = "ZA"
"Albânia" = "AL"
"Alemanha" = "DE"
"Andorra" = "AD"
"Angola" = "AO"
"Anguila" = "AI"
"Antártida" = "AQ"
"Antígua e Barbuda" = "AG"
"Arábia Saudita" = "SA"
"Argélia" = "DZ"
"Argentina" = "AR"
"Arménia" = "AM"
"Aruba" = "AW"
"Austrália" = "AU"
"Áustria" = "AT"
"Azerbaijão" = "AZ"
"Bahamas" = "BS"
"Bahrein" = "BH"
"Bangladesh" = "BD"
"Barbados" = "BB"
"Bélgica" = "BE"
"Belize" = "BZ"
"Benim" = "BJ"
"Bermudas" = "BM"
"Bielorrússia" = "BY"
"Bolívia" = "BO"
"Bósnia-Herzegovina" = "BA"
"Botsuana" = "BW"
"Brasil" = "BR"
"Brunei" = "BN"
"Bulgária" = "BG"
"Burkina Faso" = "BF"
"Burundi" = "BI"
"Butão" = "BT"
"Cabo Verde" = "CV"
"Camboja" = "KH"
"Canadá" = "CA"
"Qatar" = "QA"
"Cazaquistão" = "KZ"
"Chade" = "TD"
"Chile" = "CL"
"China" = "CN"
"Chipre" = "CY"
"Santa Sé" = "VA"
"Singapura" = "SG"
"Colômbia" = "CO"
"Comores" = "KM"
"República Democrática do Congo" = "CG"
"República Popular do Congo" = "CD"
"Coreia do Norte" = "KP"
"Coreia do Sul" = "KR"
"Costa do Marfim" = "CI"
"Costa Rica" = "CR"
"Croácia" = "HR"
"Cuba" = "CU"
"Curaçao" = "CW"
"Dinamarca" = "DK"
"Djibouti" = "DJ"
"Dominica" = "DM"
"Egito" = "EG"
"El Salvador" = "SV"
"Emirados Árabes Unidos" = "AE"
"Equador" = "EC"
"Eritreia" = "ER"
"Eslováquia" = "SK"
"Eslovénia" = "SI"
"Espanha" = "ES"
"Estados Unidos da América" = "US"
"Estónia" = "EE"
"Etiópia" = "ET"
"Fiji" = "FJ"
"Filipinas" = "PH"
"Finlândia" = "FI"
"França" = "FR"
"Gabão" = "GA"
"Gâmbia" = "GM"
"Gana" = "GH"
"Geórgia" = "GE"
"Geórgia do Sul e Ilhas Sandwich do Sul" = "GS"
"Gibraltar" = "GI"
"Granada" = "GD"
"Grécia" = "GR"
"Gronelândia" = "GL"
"Guadalupe" = "GP"
"Guam" = "GU"
"Guatemala" = "GT"
"Guernsey" = "GG"
"Guiana" = "GY"
"Guiana Francesa" = "GF"
"Guiné" = "GN"
"Guiné-Bissau" = "GW"
"Guiné Equatorial" = "GQ"
"Haiti" = "HT"
"Países Baixos" = "NL"
"Honduras" = "HN"
"Hong Kong" = "HK"
"Hungria" = "HU"
"Iémen" = "YE"
"Ilha Bouvet" = "BV"
"Ilha de Natal" = "CX"
"Ilha de Man" = "IM"
"Ilha Norfolk" = "NF"
"Ilhas Åland" = "AX"
"Ilhas Caimão" = "KY"
"Ilhas Cocos (Keeling)" = "CC"
"Ilhas Cook" = "CK"
"Ilhas Distantes dos EUA" = "UM"
"Ilha Heard e Ilhas McDonald" = "HM"
"Ilhas Faroé" = "FO"
"Ilhas Malvinas" = "FK"
"Ilhas Marianas do Norte" = "MP"
"Ilhas Marshall" = "MH"
"Ilhas Pitcairn" = "PN"
"Ilhas Salomão" = "SB"
"Ilhas Turcas e Caicos" = "TC"
"Ilhas Virgens Britânicas" = "VG"
"Ilhas Virgens Americanas" = "VI"
"Índia" = "IN"
"Indonésia" = "ID"
"Irão" = "IR"
"Iraque" = "IQ"
"Irlanda" = "IE"
"Islândia" = "IS"
"Israel" = "IL"
"Itália" = "IT"
"Jamaica" = "JM"
"Japão" = "JP"
"Jersey" = "JE"
"Jordânia" = "JO"
"Koweit" = "KW"
"Laos" = "LA"
"Lesoto" = "LS"
"Letónia" = "LV"
"Líbano" = "LB"
"Libéria" = "LR"
"Líbia" = "LY"
"Liechtenstein" = "LI"
"Lituânia" = "LT"
"Luxemburgo" = "LU"
"Macau" = "MO"
"Macedónia do Norte" = "MK"
"Madagáscar" = "MG"
"Malásia" = "MY"
"Maláui" = "MW"
"Maldivas" = "MV"
"Mali" = "ML"
"Malta" = "MT"
"Marrocos" = "MA"
"Martinica" = "MQ"
"Maurícia" = "MU"
"Mauritânia" = "MR"
"Mayotte" = "YT"
"México" = "MX"
"Mianmar (Birmânia)" = "MM"
"Micronésia" = "FM"
"Moçambique" = "MZ"
"Moldávia" = "MD"
"Mónaco" = "MC"
"Mongólia" = "MN"
"Montenegro" = "ME"
"Monserrate" = "MS"
"Namíbia" = "NA"
"Nauru" = "NR"
"Nepal" = "NP"
"Nicarágua" = "NI"
"Níger" = "NE"
"Nigéria" = "NG"
"Niue" = "NU"
"Noruega" = "NO"
"Nova Caledónia" = "NC"
"Nova Zelândia" = "NZ"
"Omã" = "OM"
"Países Baixos Caribenhos" = "BQ"
"Palau" = "PW"
"Panamá" = "PA"
"Papua-Nova Guiné" = "PG"
"Paquistão" = "PK"
"Paraguai" = "PY"
"Peru" = "PE"
"Polinésia Francesa" = "PF"
"Polónia" = "PL"
"Porto Rico" = "PR"
"Portugal" = "PT"
"Quénia" = "KE"
"Quirguistão" = "KG"
"Quiribati" = "KI"
"Reino Unido" = "GB"
"República Centro-Africana" = "CF"
"República Dominicana" = "DO"
"Camarões" = "CM"
"Chéquia" = "CZ"
"Reunião" = "RE"
"Roménia" = "RO"
"Ruanda" = "RW"
"Rússia" = "RU"
"Saara Ocidental" = "EH"
"Saint Pierre e Miquelon" = "PM"
"Samoa" = "WS"
"Samoa Americana" = "AS"
"San Marino" = "SM"
"Santa Helena" = "SH"
"Santa Lúcia" = "LC"
"São Bartolomeu" = "BL"
"São Cristóvão e Neves" = "KN"
"São Martinho" = "MF"
"São Tomé e Príncipe" = "ST"
"São Vicente e Granadinas" = "VC"
"Senegal" = "SN"
"Serra Leoa" = "SL"
"Sérvia" = "RS"
"Seychelles" = "SC"
"Síria" = "SY"
"Somália" = "SO"
"Sri Lanka" = "LK"
"Essuatíni" = "SZ"
"Sudão" = "SD"
"Sudão do Sul" = "SS"
"Suécia" = "SE"
"Suíça" = "CH"
"Suriname" = "SR"
"Svalbard e Jan Mayen" = "SJ"
"Tailândia" = "TH"
"Taiwan" = "TW"
"Tajiquistão" = "TJ"
"Tanzânia" = "TZ"
"Território Britânico do Oceano Índico" = "IO"
"Terras Austrais e Antárticas Francesas" = "TF"
"Territórios palestinos" = "PS"
"Timor-Leste" = "TL"
"Togo" = "TG"
"Tokelau" = "TK"
"Tonga" = "TO"
"Trindade e Tobago" = "TT"
"Tunísia" = "TN"
"Turquemenistão" = "TM"
"Turquia" = "TR"
"Tuvalu" = "TV"
"Ucrânia" = "UA"
"Uganda" = "UG"
"Uruguai" = "UY"
"Uzbequistão" = "UZ"
"Vanuatu" = "VU"
"Venezuela" = "VE"
"Vietname" = "VN"
"Wallis e Futuna" = "WF"
"Zâmbia" = "ZM"
"Zimbábue" = "ZW"
"Kosovo" = "XK"
